"""Pydantic схемы."""

from .auth import AuthResponse, LoginRequest, RefreshRequest, TokenPair
from .user import UserBase, UserCreate, UserRead
from .ticket import (
    TicketStatus,
    TicketPriority,
    TicketSource,
    DepartmentBase,
    DepartmentCreate,
    DepartmentRead,
    CategoryBase,
    CategoryCreate,
    CategoryRead,
    TicketBase,
    TicketCreate,
    TicketUpdate,
    TicketRead,
    TicketListRead,
    TicketWithMessages,
    MessageBase,
    MessageCreate,
    MessageRead,
    KnowledgeBaseBase,
    KnowledgeBaseCreate,
    KnowledgeBaseRead,
    AIClassificationResult,
    TicketStats,
    DepartmentStats,
    PriorityDistribution,
    SourceDistribution,
    DashboardStats,
)

__all__ = [
    "AuthResponse",
    "LoginRequest",
    "RefreshRequest",
    "TokenPair",
    "UserBase",
    "UserCreate",
    "UserRead",
    "TicketStatus",
    "TicketPriority",
    "TicketSource",
    "DepartmentBase",
    "DepartmentCreate",
    "DepartmentRead",
    "CategoryBase",
    "CategoryCreate",
    "CategoryRead",
    "TicketBase",
    "TicketCreate",
    "TicketUpdate",
    "TicketRead",
    "TicketListRead",
    "TicketWithMessages",
    "MessageBase",
    "MessageCreate",
    "MessageRead",
    "KnowledgeBaseBase",
    "KnowledgeBaseCreate",
    "KnowledgeBaseRead",
    "AIClassificationResult",
    "TicketStats",
    "DepartmentStats",
    "PriorityDistribution",
    "SourceDistribution",
    "DashboardStats",
]
